#! /bin/csh

# send a "HELLO" to the cleo client (via the cleo_hello program)
# should get a "GOODDAY" response - report 1 if so, 0 if not

set CLEOHELLOEXE = /usr/local/bin/cleo_hello
set CLEOHOST = euler.gb.nrao.edu
set CLEOPORT = 8030

set REDISHOST = localhost
set REDISPORT = 6379

set STIME = `date '+%s'`
set VALUE = `$CLEOHELLOEXE $CLEOHOST $CLEOPORT |& grep -c "GOODDAY"`

redis-cli -h $REDISHOST -p $REDISPORT HMSET CLEOHELLO VALUE $VALUE STIME $STIME >& /dev/null
