#!/bin/bash

### BEGIN INIT INFO
# Provides:          s6_observatory_gbt
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: s6_observatory_gbt
# Description:       s6_observatory_gbt thread
### END INIT INFO

# See how we were called.
case "$1" in
  start)
	su seti -c "/usr/local/bin/s6_observatory_gbt -nocleo" &
	;;
  stop)
	pkill -f s6_observatory_gbt
	;;
  restart)
	$0 stop
	sleep 1
	$0 start
	;;

  *)
	echo "Usage: s6_observatory_gbt {start|stop|restart}"
	exit 1
	;;
esac

exit 0
