#! /bin/sh
### BEGIN INIT INFO
# Provides:		    s6_observatory
# Required-Start:	$syslog $remote_fs $redis
# Required-Stop:	$syslog $remote_fs $redis
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	s6_observatory - reads AO scramnet and inserts into redis db
# Description:		    s6_observatory - reads AO scramnet and inserts into redis db
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/s6_observatory
DAEMON_ARGS="-hostname redishost"
NAME=s6_observatory
DESC=s6_observatory

RUNDIR=/var/run/s6_observatory
PIDFILE=$RUNDIR/s6_observatory.pid

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	mkdir -p $RUNDIR
	touch $PIDFILE
	chown obs:obs $RUNDIR $PIDFILE
	chmod 755 $RUNDIR
	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid obs:obs --exec $DAEMON -- $DAEMON_ARGS
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	if start-stop-daemon --stop --retry forever/QUIT/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	rm -f $PIDFILE
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;

  status)
	echo -n "$DESC is "
	if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
	then
		echo "running"
	else
		echo "not running"
		exit 1
	fi
	;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
